//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor
    {
        public Autor()
        {
            this.AutorzyKsiazkis = new HashSet<AutorzyKsiazki>();
        }
    
        public int IdAutora { get; set; }
        public int DataUrodzenia { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
    
        public virtual ICollection<AutorzyKsiazki> AutorzyKsiazkis { get; set; }
    }
}
