//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostawa
    {
        public Dostawa()
        {
            this.ElementyDostawies = new HashSet<ElementyDostawy>();
        }
    
        public int IdDostawy { get; set; }
        public int Oferent_IdOferenta { get; set; }
        public int Pracownik_IdPracownika { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Oferent Oferent { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual ICollection<ElementyDostawy> ElementyDostawies { get; set; }
    }
}
