//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementyDostawy
    {
        public int IdEgzemplarza { get; set; }
        public int IdDostawy { get; set; }
        public int Ilosc { get; set; }
    
        public virtual Dostawa Dostawa { get; set; }
        public virtual Egzemplarz Egzemplarz { get; set; }
    }
}
