//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gatunek
    {
        public Gatunek()
        {
            this.Ksiazkas = new HashSet<Ksiazka>();
        }
    
        public int IdGatunku { get; set; }
        public string NazwaGatunku { get; set; }
    
        public virtual ICollection<Ksiazka> Ksiazkas { get; set; }
    }
}
