//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazka
    {
        public Ksiazka()
        {
            this.AutorzyKsiazkis = new HashSet<AutorzyKsiazki>();
            this.Egzemplarzs = new HashSet<Egzemplarz>();
        }
    
        public int IdKsiazki { get; set; }
        public string Opis { get; set; }
        public string Tytul { get; set; }
        public int Gatunek_IdGatunku { get; set; }
    
        public virtual ICollection<AutorzyKsiazki> AutorzyKsiazkis { get; set; }
        public virtual ICollection<Egzemplarz> Egzemplarzs { get; set; }
        public virtual Gatunek Gatunek { get; set; }
    }
}
