//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KsiegarniaEntities : DbContext
    {
        public KsiegarniaEntities()
            : base("name=KsiegarniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<AutorzyKsiazki> AutorzyKsiazkis { get; set; }
        public virtual DbSet<Dostawa> Dostawas { get; set; }
        public virtual DbSet<Egzemplarz> Egzemplarzs { get; set; }
        public virtual DbSet<ElementyDostawy> ElementyDostawies { get; set; }
        public virtual DbSet<ElementyZamowienia> ElementyZamowienias { get; set; }
        public virtual DbSet<Gatunek> Gatuneks { get; set; }
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<Ksiazka> Ksiazkas { get; set; }
        public virtual DbSet<Oferent> Oferents { get; set; }
        public virtual DbSet<OfertaOferenta> OfertaOferentas { get; set; }
        public virtual DbSet<Pracownik> Pracowniks { get; set; }
        public virtual DbSet<Rabat> Rabats { get; set; }
        public virtual DbSet<RealizacjaZamowienia> RealizacjaZamowienias { get; set; }
        public virtual DbSet<RealizacjeReklamacji> RealizacjeReklamacjis { get; set; }
        public virtual DbSet<Reklamacja> Reklamacjas { get; set; }
        public virtual DbSet<RodzajWysylki> RodzajWysylkis { get; set; }
        public virtual DbSet<Wydawnictwo> Wydawnictwoes { get; set; }
        public virtual DbSet<Zamowieny> Zamowienies { get; set; }
    }
}
