//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public Pracownik()
        {
            this.Dostawas = new HashSet<Dostawa>();
            this.Zamowienies = new HashSet<Zamowieny>();
        }
    
        public int IdPracownika { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
    
        public virtual ICollection<Dostawa> Dostawas { get; set; }
        public virtual ICollection<Zamowieny> Zamowienies { get; set; }
    }
}
