//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklamacja
    {
        public int IdReklamacji { get; set; }
        public string Opis { get; set; }
        public bool Typ { get; set; }
        public int IdTypu { get; set; }
        public int RealizacjeReklamacji_IdRealizacji { get; set; }
    
        public virtual RealizacjeReklamacji RealizacjeReklamacji { get; set; }
    }
}
