//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wydawnictwo
    {
        public Wydawnictwo()
        {
            this.Egzemplarzs = new HashSet<Egzemplarz>();
        }
    
        public int IdWydawnictwa { get; set; }
        public string NazwaWydawnictwa { get; set; }
    
        public virtual ICollection<Egzemplarz> Egzemplarzs { get; set; }
    }
}
