//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowieny
    {
        public Zamowieny()
        {
            this.ElementyZamowienias = new HashSet<ElementyZamowienia>();
        }
    
        public int IdZamowienia { get; set; }
        public int KosztZamowienia { get; set; }
        public int Klient_IdKlienta { get; set; }
        public int Pracownik_IdPracownika { get; set; }
        public int Rabat_IdRabatu { get; set; }
        public int RealizacjaZamowienia_IdRealizacji { get; set; }
        public int RodzajuWysylki_IdRodzajWysylki { get; set; }
    
        public virtual ICollection<ElementyZamowienia> ElementyZamowienias { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Rabat Rabat { get; set; }
        public virtual RealizacjaZamowienia RealizacjaZamowienia { get; set; }
        public virtual RodzajWysylki RodzajWysylki { get; set; }
    }
}
